---
- hosts: all
  tasks:
    - name: Deploy the service {{ item.project_name }}
      include_role:
        name: deployer

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
